export const DEFAULT_HOME_TILES = [
  { icon: "BedDouble", title: "Hourly / Short Stay", desc: "Short stays, day use, hourly rate", pill: "Explore", to: "/hourly-rooms" },
  { icon: "Users", title: "Roommates", desc: "Meet people with similar budgets and plans", pill: "Find", to: "/roommates" },
  { icon: "HeartHandshake", title: "Social Work", desc: "Find community services and support in Indore", pill: "Explore", to: "/social-work" },
  { icon: "PackageOpen", title: "Donate Old Things", desc: "Arrange a pickup for useful items you no longer need", pill: "Donate", to: "/donate" },
  { icon: "HeartPulse", title: "Blood Requests", desc: "Request help or learn about blood donation", pill: "Explore", to: "/blood" },
  { icon: "Castle", title: "Villas", desc: "Book a private villa for a stay or party", pill: "Explore", to: "/villas" },
  { icon: "Banknote", title: "Student Loans", desc: "Help finding a loan for rent or fees", pill: "Apply", action: "loan" },
  { icon: "Bike", title: "Vehicle Rental", desc: "Bike and scooty rental by the day", pill: "Explore", to: "/vehicles" },
  { icon: "UtensilsCrossed", title: "Food", desc: "Mess near you with today's menu", pill: "Explore", to: "/mess" },
  { icon: "Shirt", title: "Laundry", desc: "Find nearby laundries and order clothes", pill: "Explore", to: "/laundry" },
  { icon: "Sparkles", title: "Cleaning", desc: "Room and bathroom cleaning", pill: "Explore", to: "/services/cleaning" },
  { icon: "Truck", title: "Moving", desc: "Easy shifting to your new place", pill: "Explore", to: "/services/packers" },
  { icon: "Sofa", title: "Furniture Rental", desc: "Bed, cooler, AC, fridge on rent", pill: "Explore", to: "/furniture" },
  { icon: "Wifi", title: "Wi-Fi & RO", desc: "Broadband and RO purifier service", pill: "Explore", to: "/services/wifi" },
  { icon: "Wrench", title: "Repairs", desc: "Cooler, AC and geyser repair", pill: "Explore", to: "/services/appliance-repair" },
  { icon: "BookOpen", title: "Study Support", desc: "Libraries, tutors and printing help", pill: "Explore", to: "/services/study-support" },
  { icon: "FileText", title: "Rent Agreement", desc: "Agreement and police verification", pill: "Explore", to: "/services/rent-agreement" },
  { icon: "LayoutGrid", title: "More Services", desc: "See everything RoomSlider offers", pill: "View All", to: "/explore" },
];
